/** Single source of env key string literals. */
export const EnvKeys = {
  PORT: 'PORT',
  TRUST_PROXY: 'TRUST_PROXY',
  DATABASE_URL: 'DATABASE_URL',
  DIRECT_URL: 'DIRECT_URL',
  JWT_SECRET: 'JWT_SECRET',
  OTP_PEPPER: 'OTP_PEPPER',
  RAZORPAY_KEY_ID: 'RAZORPAY_KEY_ID',
  RAZORPAY_KEY_SECRET: 'RAZORPAY_KEY_SECRET',
  RAZORPAY_WEBHOOK_SECRET: 'RAZORPAY_WEBHOOK_SECRET',
  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_JWT_SECRET: 'SUPABASE_JWT_SECRET',
  SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
} as const;

export type EnvKey = (typeof EnvKeys)[keyof typeof EnvKeys];
